Repository unit8co/darts, pull requests merged in 2025-04, with the labels that each got.

#2776 Fix/categorical validation features
  darts/models/forecasting/catboost_model.py
  darts/models/forecasting/regression_model.py
  darts/tests/models/forecasting/test_regression_models.py
Labels: bug

#2771 Add support for `numpy>=2.0.0`
  .github/scripts/libomp-Linux.sh
  .github/scripts/libomp-macOS.sh
  .github/workflows/develop.yml
  .github/workflows/doc.yml
  .github/workflows/merge.yml
  .github/workflows/release.yml
  .github/workflows/update-cache.yml
  CHANGELOG.md
  darts/datasets/__init__.py
  darts/tests/models/forecasting/test_conformal_model.py
  darts/tests/models/forecasting/test_torch_forecasting_model.py
  darts/tests/optional_deps/test_onnx.py
  darts/tests/utils/historical_forecasts/__init__.py
  darts/tests/utils/test_timeseries_generation.py
  darts/utils/data/tabularization.py
  requirements/core.txt
Labels: devops

#2774 Rename RegressionModel into SKLearnModel and RandomForest to RandomForestModel
  .github/workflows/merge.yml
  CHANGELOG.md
  README.md
  darts/dataprocessing/encoders/encoder_base.py
  darts/dataprocessing/encoders/encoders.py
  darts/explainability/explainability_result.py
  darts/explainability/shap_explainer.py
  darts/models/__init__.py
  darts/models/forecasting/__init__.py
  darts/models/forecasting/catboost_model.py
  darts/models/forecasting/forecasting_model.py
  darts/models/forecasting/lgbm.py
  darts/models/forecasting/linear_regression_model.py
  darts/models/forecasting/random_forest.py
  darts/models/forecasting/regression_ensemble_model.py
  darts/models/forecasting/sklearn_model.py
  darts/models/forecasting/xgboost.py
  darts/tests/ad/test_anomaly_model.py
  darts/tests/dataprocessing/encoders/test_covariate_index_generators.py
  darts/tests/explainability/test_shap_explainer.py
  darts/tests/models/forecasting/test_backtesting.py
  darts/tests/models/forecasting/test_ensemble_models.py
  darts/tests/models/forecasting/test_local_forecasting_models.py
  darts/tests/models/forecasting/test_regression_ensemble_model.py
  darts/tests/models/forecasting/test_residuals.py
  darts/tests/models/forecasting/test_sklearn_models.py
  darts/utils/data/tabularization.py
  darts/utils/historical_forecasts/optimized_historical_forecasts_regression.py
  darts/utils/historical_forecasts/utils.py
  darts/utils/likelihood_models/base.py
  darts/utils/likelihood_models/sklearn.py
  docs/source/examples.rst
  docs/userguide/covariates.md
  docs/userguide/forecasting_overview.md
  examples/00-quickstart.ipynb
  examples/14-transfer-learning.ipynb
  examples/19-EnsembleModel-examples.ipynb
  examples/20-SKLearnModel-examples.ipynb
  examples/22-anomaly-detection-examples.ipynb
Labels: improvement
